//go:build !ignore_autogenerated

/*
Copyright 2026 SAP SE.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminCredentialsSecretRef) DeepCopyInto(out *AdminCredentialsSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminCredentialsSecretRef.
func (in *AdminCredentialsSecretRef) DeepCopy() *AdminCredentialsSecretRef {
	if in == nil {
		return nil
	}
	out := new(AdminCredentialsSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChildResourcesReference) DeepCopyInto(out *ChildResourcesReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChildResourcesReference.
func (in *ChildResourcesReference) DeepCopy() *ChildResourcesReference {
	if in == nil {
		return nil
	}
	out := new(ChildResourcesReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HANACloudObservation) DeepCopyInto(out *HANACloudObservation) {
	*out = *in
	if in.MappingID != nil {
		in, out := &in.MappingID, &out.MappingID
		*out = new(MappingID)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HANACloudObservation.
func (in *HANACloudObservation) DeepCopy() *HANACloudObservation {
	if in == nil {
		return nil
	}
	out := new(HANACloudObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceMapping) DeepCopyInto(out *InstanceMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceMapping.
func (in *InstanceMapping) DeepCopy() *InstanceMapping {
	if in == nil {
		return nil
	}
	out := new(InstanceMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceMappingList) DeepCopyInto(out *InstanceMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstanceMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceMappingList.
func (in *InstanceMappingList) DeepCopy() *InstanceMappingList {
	if in == nil {
		return nil
	}
	out := new(InstanceMappingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceMappingObservation) DeepCopyInto(out *InstanceMappingObservation) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceMappingObservation.
func (in *InstanceMappingObservation) DeepCopy() *InstanceMappingObservation {
	if in == nil {
		return nil
	}
	out := new(InstanceMappingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceMappingParameters) DeepCopyInto(out *InstanceMappingParameters) {
	*out = *in
	if in.SecondaryID != nil {
		in, out := &in.SecondaryID, &out.SecondaryID
		*out = new(string)
		**out = **in
	}
	out.AdminCredentialsSecretRef = in.AdminCredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceMappingParameters.
func (in *InstanceMappingParameters) DeepCopy() *InstanceMappingParameters {
	if in == nil {
		return nil
	}
	out := new(InstanceMappingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceMappingSpec) DeepCopyInto(out *InstanceMappingSpec) {
	*out = *in
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceMappingSpec.
func (in *InstanceMappingSpec) DeepCopy() *InstanceMappingSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceMappingStatus) DeepCopyInto(out *InstanceMappingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceMappingStatus.
func (in *InstanceMappingStatus) DeepCopy() *InstanceMappingStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceMappingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KymaClusterObservation) DeepCopyInto(out *KymaClusterObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KymaClusterObservation.
func (in *KymaClusterObservation) DeepCopy() *KymaClusterObservation {
	if in == nil {
		return nil
	}
	out := new(KymaClusterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KymaConnectionReference) DeepCopyInto(out *KymaConnectionReference) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KymaConnectionReference.
func (in *KymaConnectionReference) DeepCopy() *KymaConnectionReference {
	if in == nil {
		return nil
	}
	out := new(KymaConnectionReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KymaInstanceMapping) DeepCopyInto(out *KymaInstanceMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KymaInstanceMapping.
func (in *KymaInstanceMapping) DeepCopy() *KymaInstanceMapping {
	if in == nil {
		return nil
	}
	out := new(KymaInstanceMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KymaInstanceMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KymaInstanceMappingList) DeepCopyInto(out *KymaInstanceMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KymaInstanceMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KymaInstanceMappingList.
func (in *KymaInstanceMappingList) DeepCopy() *KymaInstanceMappingList {
	if in == nil {
		return nil
	}
	out := new(KymaInstanceMappingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KymaInstanceMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KymaInstanceMappingObservation) DeepCopyInto(out *KymaInstanceMappingObservation) {
	*out = *in
	if in.Kyma != nil {
		in, out := &in.Kyma, &out.Kyma
		*out = new(KymaClusterObservation)
		**out = **in
	}
	if in.Hana != nil {
		in, out := &in.Hana, &out.Hana
		*out = new(HANACloudObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ChildResources != nil {
		in, out := &in.ChildResources, &out.ChildResources
		*out = new(ChildResourcesReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KymaInstanceMappingObservation.
func (in *KymaInstanceMappingObservation) DeepCopy() *KymaInstanceMappingObservation {
	if in == nil {
		return nil
	}
	out := new(KymaInstanceMappingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KymaInstanceMappingParameters) DeepCopyInto(out *KymaInstanceMappingParameters) {
	*out = *in
	if in.KymaConnectionRef != nil {
		in, out := &in.KymaConnectionRef, &out.KymaConnectionRef
		*out = new(KymaConnectionReference)
		**out = **in
	}
	out.AdminBindingRef = in.AdminBindingRef
	out.ServiceInstanceRef = in.ServiceInstanceRef
	if in.TargetNamespace != nil {
		in, out := &in.TargetNamespace, &out.TargetNamespace
		*out = new(string)
		**out = **in
	}
	if in.ClusterIDConfigMapRef != nil {
		in, out := &in.ClusterIDConfigMapRef, &out.ClusterIDConfigMapRef
		*out = new(ResourceReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KymaInstanceMappingParameters.
func (in *KymaInstanceMappingParameters) DeepCopy() *KymaInstanceMappingParameters {
	if in == nil {
		return nil
	}
	out := new(KymaInstanceMappingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KymaInstanceMappingSpec) DeepCopyInto(out *KymaInstanceMappingSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KymaInstanceMappingSpec.
func (in *KymaInstanceMappingSpec) DeepCopy() *KymaInstanceMappingSpec {
	if in == nil {
		return nil
	}
	out := new(KymaInstanceMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KymaInstanceMappingStatus) DeepCopyInto(out *KymaInstanceMappingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KymaInstanceMappingStatus.
func (in *KymaInstanceMappingStatus) DeepCopy() *KymaInstanceMappingStatus {
	if in == nil {
		return nil
	}
	out := new(KymaInstanceMappingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingID) DeepCopyInto(out *MappingID) {
	*out = *in
	if in.SecondaryID != nil {
		in, out := &in.SecondaryID, &out.SecondaryID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingID.
func (in *MappingID) DeepCopy() *MappingID {
	if in == nil {
		return nil
	}
	out := new(MappingID)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}
