# Example: KymaInstanceMapping for cross-cluster HANA Cloud instance mapping
#
# This example demonstrates how to create a HANA Cloud instance mapping from a management
# cluster that fetches configuration from a remote Kyma cluster.
#
# NOTE: For single-cluster deployments where the provider runs on the same cluster as the
# ServiceInstance, you can omit the kymaConnectionRef entirely. See kymainstancemapping-local.yaml.
#
# Prerequisites:
# 1. Management cluster with crossplane-provider-hana installed
# 2. Remote Kyma cluster with:
#    - BTP Service Operator installed
#    - HANA Cloud ServiceInstance created
#    - Admin API ServiceBinding created
# 3. Kubeconfig for remote Kyma cluster stored as Secret

---
# Step 1: Store the Kyma cluster kubeconfig on the management cluster
# Export kubeconfig from your Kyma cluster and create this secret:
#   kubectl config view --minify --flatten > kyma-kubeconfig.yaml
#   kubectl create secret generic kyma-cluster-kubeconfig \
#     --from-file=kubeconfig=kyma-kubeconfig.yaml \
#     -n crossplane-system
apiVersion: v1
kind: Secret
metadata:
  name: kyma-cluster-kubeconfig
  namespace: crossplane-system
type: Opaque
data:
  # Base64-encoded kubeconfig file for the remote Kyma cluster
  # Example: cat kyma-kubeconfig.yaml | base64
  kubeconfig: <base64-encoded-kubeconfig>

---
# Step 2: ProviderConfig (placeholder - admin API credentials come from Kyma cluster)
apiVersion: hana.orchestrate.cloud.sap/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: HanaConnectionSecret
    connectionSecretRef:
      # This is not used for KymaInstanceMapping since credentials come from the remote cluster
      # However, ProviderConfig is still required by Crossplane architecture
      name: dummy-creds
      namespace: crossplane-system

---
# Step 3: KymaInstanceMapping resource
apiVersion: inventory.hana.orchestrate.cloud.sap/v1alpha1
kind: KymaInstanceMapping
metadata:
  name: production-hana-mapping
spec:
  providerConfigRef:
    name: default

  forProvider:
    # Connection to remote Kyma cluster
    # OPTIONAL: Omit this section for single-cluster deployments
    # When omitted, the controller uses the local cluster where it's running
    kymaConnectionRef:
      secretRef:
        name: kyma-cluster-kubeconfig
        namespace: crossplane-system
      kubeconfigKey: kubeconfig  # Key in the secret containing kubeconfig (default: "kubeconfig")

    # ServiceInstance on remote Kyma cluster (contains HANA Cloud instance GUID)
    serviceInstanceRef:
      name: my-hana-instance
      namespace: default

    # ServiceBinding on remote Kyma cluster (provides admin API credentials)
    adminBindingRef:
      name: hana-admin-api-binding
      namespace: default

    # Target namespace on Kyma cluster to map
    targetNamespace: my-application

    # Optional: ConfigMap on Kyma cluster containing CLUSTER_ID
    # If not specified, defaults to kyma-system/sap-btp-operator-config
    clusterIdConfigMapRef:
      name: sap-btp-operator-config
      namespace: kyma-system

    # Set as default mapping for the namespace
    isDefault: false

---
# Resources expected on the remote Kyma cluster:

# 1. HANA Cloud ServiceInstance (on Kyma cluster)
# apiVersion: services.cloud.sap.com/v1
# kind: ServiceInstance
# metadata:
#   name: my-hana-instance
#   namespace: default
# spec:
#   serviceOfferingName: hana-cloud
#   servicePlanName: hana
#   parameters:
#     data:
#       memory: 32
#       vcpu: 2
# status:
#   instanceID: "cf923d7d-7661-48f2-aaa2-d4dbb151a708"  # ← Extracted by controller
#   ready: true

# 2. Admin API ServiceInstance (on Kyma cluster)
# apiVersion: services.cloud.sap.com/v1
# kind: ServiceInstance
# metadata:
#   name: hana-admin-api
#   namespace: default
# spec:
#   serviceOfferingName: hana-cloud
#   servicePlanName: admin-api-access
#   parameters:
#     data:
#       platform: "kubernetes"

# 3. Admin API ServiceBinding (on Kyma cluster)
# apiVersion: services.cloud.sap.com/v1
# kind: ServiceBinding
# metadata:
#   name: hana-admin-api-binding
#   namespace: default
# spec:
#   serviceInstanceName: hana-admin-api
#   secretName: hana-admin-api-secret  # ← Extracted by controller

# 4. Admin API credentials secret (auto-created by BTP operator on Kyma cluster)
# apiVersion: v1
# kind: Secret
# metadata:
#   name: hana-admin-api-secret
#   namespace: default
# data:
#   url: <base64-encoded-url>      # ← Extracted by controller
#   uaa: <base64-encoded-json>     # ← Extracted by controller

# 5. BTP Operator ConfigMap (on Kyma cluster)
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: sap-btp-operator-config
#   namespace: kyma-system
# data:
#   CLUSTER_ID: "shoot--prod--cluster-abc123"  # ← Extracted by controller

---
# Expected status after successful reconciliation:
#
# status:
#   conditions:
#   - type: Ready
#     status: "True"
#   - type: Synced
#     status: "True"
#   atProvider:
#     kyma:
#       serviceInstanceID: "cf923d7d-7661-48f2-aaa2-d4dbb151a708"
#       clusterID: "shoot--prod--cluster-abc123"
#       serviceInstanceName: "my-hana-instance"
#       serviceInstanceReady: true
#     hana:
#       mappingId:
#         serviceInstanceID: "cf923d7d-7661-48f2-aaa2-d4dbb151a708"
#         primaryID: "shoot--prod--cluster-abc123"
#         secondaryID: "my-application"
#       ready: true
