apiVersion: schema.hana.orchestrate.cloud.sap/v1alpha1
kind: DbSchema
metadata:
  name: example-schema
spec:
  forProvider:
    schemaName: EXAMPLE
    owner: DBADMIN
  providerConfigRef:
    name: example
