# Release builds and publish a new release.
# Vars:
# REGISTRY_URL: registry url for the container registry

name: Release

on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: 'specify the release version in the semver format v[major].[minor].[patch] e.g. v0.0.0'
        required: true

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
# Permissions need to be added here at the top level, since permissions
# to called workflows can only be reduced.
permissions:
  contents: write
  packages: write

jobs:
  run-pre-checks:
    uses: SAP/crossplane-provider-btp/.github/workflows/check-all-pre-checks.lib.yaml@main
    permissions:
      contents: read

  build-and-publish:
    needs:
    - run-pre-checks
    uses: SAP/crossplane-provider-btp/.github/workflows/release-build-publish.lib.yaml@main
    with:
      version: ${{ github.event.inputs.nextVersion }}
      release_type: release
    secrets: inherit
