# The on.pull_request pipeline runs on changes to a pull request. With this trigger, the pipeline never receives secrets from gh and the GITHUB_TOKEN is read only.
# Therefore, we can not run our e2e tests here, this needs to be done in an on.pull_request_target pipeline.
name: PR Tests and Pre-Checks

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
    paths-ignore:
      - '*.md'

permissions:
  contents: read

jobs:
  run-pre-checks:
    uses: SAP/crossplane-provider-btp/.github/workflows/check-all-pre-checks.lib.yaml@main
